# Generated by Django 4.2.3 on 2023-11-24 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Administrador'), (2, 'Cliente'), (3, 'Chofer')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='viaje',
            fields=[
                ('idViaje', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('capacidadVehiculo', models.IntegerField()),
                ('vehiculo', models.CharField(max_length=30)),
                ('tarifa', models.IntegerField()),
                ('destino', models.CharField(max_length=30)),
                ('origen', models.CharField(max_length=30)),
                ('chofer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
    ]
