# Generated by Django 4.2.3 on 2023-11-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Administrador'), (2, 'Cliente'), (3, 'Chofer')], null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
