# Generated by Django 4.2.3 on 2023-11-22 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_role_alter_usuario_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='viaje',
            fields=[
                ('idViaje', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('capacidadVehiculo', models.IntegerField()),
                ('vehiculo', models.CharField(max_length=30)),
                ('tarifa', models.IntegerField()),
                ('destino', models.CharField(max_length=30)),
                ('origen', models.CharField(max_length=30)),
                ('idChofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
    ]
